name: TestGPU

on:
  workflow_dispatch:

jobs:
  test-gpu:
    timeout-minutes: 5
    # https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nvidia.ngc_azure_17_11
    runs-on:
      group: gpu

    steps:
      - uses: actions/checkout@v4

      - name: Report Runner Specs
        run: | 
          lscpu 
          free -h 
          df -h
      
      - name: Report GPU specs
        run: | 
          nvidia-smi
