# Create a GitHub Release
name: Data Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: Tag to apply to release
        default: test
      runid:
        type: number
        required: true
        description: Run ID with workflow artifacts to be attached to release
        default: 8087667730
          
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    # NOTE: GH_PAT required to access artifacts from another workflow
    - uses: actions/download-artifact@v4
      with:
        name: merged
        github-token: ${{ secrets.GH_PAT }}
        run-id: ${{ inputs.runid }}

    - name: List current directory
      run: ls -l *

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
        artifacts: "S1_*/*.tif,S1_*/*.txt"
        body: "a test release"
